# Generated by Django 5.0 on 2025-09-21 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("flagged", "Flagged"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("suspend", "Suspend User"),
                            ("reactivate", "Reactivate User"),
                            ("delete", "Delete User"),
                            ("change_role", "Change User Role"),
                            ("flag", "Flag User"),
                            ("unflag", "Unflag User"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the action taken"),
                ),
                (
                    "previous_value",
                    models.CharField(
                        blank=True,
                        help_text="Previous value before change",
                        max_length=200,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True, help_text="New value after change", max_length=200
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_action_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Action Log",
                "verbose_name_plural": "Admin Action Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
