# Generated by Django 5.0 on 2025-10-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_customuser_status_adminactionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("public", "Public - Everything visible"),
                            ("limited", "Limited - Basic info only"),
                            ("private", "Private - Minimal visibility"),
                            ("custom", "Custom - Manual selection"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "show_full_name",
                    models.BooleanField(default=True, help_text="Show your full name"),
                ),
                (
                    "show_profile_photo",
                    models.BooleanField(
                        default=True, help_text="Show your profile photo"
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False, help_text="Show your email address"
                    ),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False, help_text="Show your phone number"
                    ),
                ),
                (
                    "location_visibility",
                    models.CharField(
                        choices=[
                            ("full", "Full Address"),
                            ("city", "City Only"),
                            ("state", "State Only"),
                            ("hidden", "Hidden"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                (
                    "show_current_employer",
                    models.BooleanField(
                        default=True, help_text="Show your current employer"
                    ),
                ),
                (
                    "work_history_visibility",
                    models.CharField(
                        choices=[
                            ("all", "Show All"),
                            ("partial", "Show Partial (Last 2 positions)"),
                            ("hidden", "Hidden"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "show_education",
                    models.BooleanField(
                        default=True, help_text="Show education history"
                    ),
                ),
                (
                    "show_skills",
                    models.BooleanField(
                        default=True, help_text="Show skills and certifications"
                    ),
                ),
                (
                    "show_resume",
                    models.BooleanField(
                        default=True, help_text="Allow resume downloads"
                    ),
                ),
                (
                    "searchable_by_recruiters",
                    models.BooleanField(
                        default=True, help_text="Make profile searchable by recruiters"
                    ),
                ),
                (
                    "allow_recruiter_messages",
                    models.BooleanField(
                        default=True, help_text="Allow recruiters to message you"
                    ),
                ),
                (
                    "show_salary_expectations",
                    models.BooleanField(
                        default=False, help_text="Show salary expectations"
                    ),
                ),
                (
                    "blocked_companies",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of company names to block",
                    ),
                ),
                (
                    "anonymous_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Apply anonymously - hide identifying information",
                    ),
                ),
                (
                    "notify_on_profile_view",
                    models.BooleanField(
                        default=False,
                        help_text="Email notification when profile is viewed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to="profiles.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Settings",
                "verbose_name_plural": "Privacy Settings",
            },
        ),
    ]
