# Generated by Django 5.0 on 2025-10-28 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_remove_jobposting_jobs_jobpos_moderat_3d688a_idx_and_more"),
        ("profiles", "0005_conversation_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("application_status", "Application Status Change"),
                            ("interview", "Interview Invitation"),
                            ("offer", "Job Offer"),
                            ("message", "New Message"),
                            ("profile_view", "Profile Viewed"),
                            ("job_match", "Job Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="jobs.jobposting",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="profiles_no_recipie_037c81_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="profiles_no_recipie_d94d1b_idx",
                    ),
                ],
            },
        ),
    ]
