# Generated by Django 5.0 on 2025-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_conversation_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="commute_radius_miles",
            field=models.IntegerField(
                default=25, help_text="Preferred commute radius in miles"
            ),
        ),
    ]
