# Generated by Django 5.0 on 2025-11-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_jobseekerprofile_commute_radius_miles"),
        ("profiles", "0006_notification"),
    ]

    operations = []
