# Generated by Django 5.0 on 2025-11-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_merge_20251113_1929"),
        ("profiles", "0007_merge_20251118_2226"),
    ]

    operations = []
