# Generated by Django 5.0 on 2025-11-19 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_merge_20251119_2129"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("job_view", "Job View"),
                            ("job_application", "Job Application"),
                            ("profile_view", "Profile View"),
                            ("profile_edit", "Profile Edit"),
                            ("job_post", "Job Post"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional context like job ID, search terms, etc.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="profiles_us_user_id_9a91e5_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="profiles_us_activit_1bde58_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="profiles_us_timesta_9a7079_idx"
                    ),
                ],
            },
        ),
    ]
