# Generated by Django 5.0 on 2025-09-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Job Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "work_location",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("on_site", "On Site"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="on_site",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "salary_period",
                    models.CharField(
                        choices=[
                            ("hourly", "Per Hour"),
                            ("monthly", "Per Month"),
                            ("yearly", "Per Year"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewed", "Interviewed"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("recruiter_notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "years_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_skills",
                        to="jobs.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_required", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["is_active", "posted_at"], name="jobs_jobpos_is_acti_a445c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["category", "location"], name="jobs_jobpos_categor_272d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["employment_type", "experience_level"],
                name="jobs_jobpos_employm_a66777_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="jobs_jobapp_job_id_08192b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applicant", "status"], name="jobs_jobapp_applica_089491_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "applicant")},
        ),
        migrations.AlterUniqueTogether(
            name="jobskill",
            unique_together={("job", "name")},
        ),
    ]
