# Generated by Django 5.0 on 2025-09-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='visa_sponsorship',
            field=models.BooleanField(default=False, help_text='Does this job offer visa sponsorship?'),
        ),
    ]
