# Generated by Django 5.0 on 2025-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_jobapplication_status_applicationstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="interview_date",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled interview date and time", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted Offer"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                help_text="Final outcome of the application",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("review", "Under Review"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="recruiter_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes from recruiter"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("review", "Under Review"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                    ("closed", "Closed"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
