# Generated by Django 5.0 on 2025-09-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_jobapplication_interview_date_jobapplication_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="jobs.jobcategory",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
