# Generated by Django 5.0 on 2025-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobposting_status_alter_jobposting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
