# Generated by Django 5.0 on 2025-10-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobposting_admin_notes_jobposting_moderated_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobposting",
            name="jobs_jobpos_moderat_3d688a_idx",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="moderated_at",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="moderated_by",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="moderation_status",
        ),
    ]
