# Generated by Django 5.0 on 2025-10-22 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_jobseekerprofile_latitude_jobseekerprofile_longitude"),
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="last_notified_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time notifications were sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="last_search_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time this search was run", null=True
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("daily", "Daily Digest"),
                    ("weekly", "Weekly Digest"),
                ],
                default="daily",
                help_text="How often to send notifications",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="notify_on_new_matches",
            field=models.BooleanField(
                default=True,
                help_text="Send notifications when new candidates match this search",
            ),
        ),
        migrations.CreateModel(
            name="SearchMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_new_match",
                    models.BooleanField(
                        default=True,
                        help_text="True if this is a new match since last notification",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this match has been included in a notification",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_matches",
                        to="profiles.jobseekerprofile",
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="recruiters.savedsearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["saved_search", "is_new_match"],
                        name="recruiters__saved_s_4549d4_idx",
                    ),
                    models.Index(
                        fields=["matched_at"], name="recruiters__matched_965fc9_idx"
                    ),
                ],
                "unique_together": {("saved_search", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="SearchNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        help_text="Type of notification sent",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matches_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of new matches included in this notification",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recruiter has read this notification",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email was successfully sent",
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="recruiters.savedsearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["saved_search", "is_read"],
                        name="recruiters__saved_s_78a7a7_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="recruiters__sent_at_b789f1_idx"
                    ),
                ],
            },
        ),
    ]
